### ISSUE TITLE
Null trapping on isToLowerCase

### ISSUE THREAD

**Issue by the-arinc** [LostLogic/Lexicon-DJ---Track-Helper-Plugin#1]
<img width="535" alt="image" src="https://github.com/user-attachments/assets/335021c1-a238-422b-954e-f67e47d939f2">

I get this issue when attempting to use the named cues to memory cues plugin on a bunch of tracks. Initial thoughts are quite simply that the plugin was attempting to run on a track that didn't have any special characters in the cue names (so I have used the same convention of searching for an asterisk "*" in cue names at the start of cues like so:

<img width="646" alt="image" src="https://github.com/user-attachments/assets/055aad45-7459-4eca-b008-860af69b572a">

However going step by step through the tracks identified that didn't seem to be the case. I eventually found the culprit track which is this one, you can see the cues in white which have null text in the cue name (cue 9 and 10), that is because those are memory cues that I added in rekordbox and synced back. So currently the plugin is falling over when **trying to read those two cues with empty text in the cue name** is my evaluation.

<img width="1216" alt="image" src="https://github.com/user-attachments/assets/4e530bb9-259d-4b42-95ed-6692d1bbfdd2">

**Comment by the-arinc** [comment]
Indeed renaming those two null cues to give them value text, and then re-running the plugin works as expected: 
<img width="1310" alt="image" src="https://github.com/user-attachments/assets/42f09f94-93fe-4306-8d74-e09a53982a63">

**Comment by the-arinc** [comment]
I've corrected this in the related Pull Request. Apologies that has two commits in there (the first one is just me refactoring my git area for Plugins so adding DS_Store to gitignore since Mac's always make that file, and Christian's example plugin) so I won't be offended if you reject that as obviously you won't want that in your repository! Apologies I am quite new to using GitHub! 🙂

**Comment by LostLogic** [comment]
No worries! And thanks for taking the time to submit a fix for it. Closing the issue
